package exception;

import java.util.InputMismatchException;
import java.util.Scanner;

public class ExceptionTest {

	public static void main(String[] args) {
		int result = 0;
		Scanner sc = new Scanner(System.in);
		
		System.out.println("정수를 입력하세요 >>>");
		
		try {
			int num = sc.nextInt();
			result = 3 / num;
			System.out.println("입력한 수는 " + num + "입니다.");
			System.out.println("결과는 " + result + "입니다.");
		} catch (InputMismatchException e) {
			// TODO Auto-generated catch block
//			e.printStackTrace(); // 에러의 경로를 추적하여 출력해주는 메소드 (빨간 글씨)
			System.out.println("정수를 입력하라니까!!");
		} catch (ArithmeticException e) {
			System.out.println((e.getMessage()));
			System.out.println("0으로는 못나눈다고!!");

		}
		


	}

}
