package exception;

public class ExceptionTest4 {

	public static void method1() {
		boolean isSuccess = true;
		
		try {
			System.out.println("\t method1 : 로직 처리");
			if (isSuccess) {
				System.out.println("\t method1 : 실행");
				return;
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		System.out.println("\t method1 : 필수 로직 처리 완료");
	}
	
	public static void method2() {
		boolean isSuccess = true;
		
			try {
				System.out.println("\t method2 : 로직 처리");
				if (isSuccess) {
					System.out.println("\t method2 : 실행");
					return;
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				System.out.println("\t method2 : 필수 로직 처리 완료");
			}
		
	}
	
	public static void main(String[] args) {
		method1();
		
	}

}
